name: PR Notification to Teams

on:
  pull_request:
    types: [opened, closed, reopened]

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Microsoft Teams
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          notification-summary: 'Pull Request Update'
          notification-color: '17a2b8'
          timezone: 'America/Denver'
