name: Notify Teams on PR Creation

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR Notification to Teams
        uses: rlespinasse/github-action-teams-notification@v1
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          pr_title: ${{ github.event.pull_request.title }}
          pr_url: ${{ github.event.pull_request.html_url }}
