name: Notify Teams on PR

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Teams
        uses: teamsnotify/teamsnotify@v1
        env:
          DISCORD_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK_URL }}
        with:
          args: "📣 New PR created: ${{ github.event.pull_request.title }} by ${{ github.actor }}"
